### ISSUE TITLE
faceshifter

### ISSUE THREAD

**Issue by molo32** [woctezuma/stylegan2-projecting-images#11]
can you implement faceshifter to swap identity between latent codes?
like this:
https://github.com/dayu1979/stylegan2-faceshifter

**Comment by woctezuma** [comment]
This is out of scope of this project.

Plus, it would be simpler if the authors made their code pubic:
-   https://github.com/dayu1979/stylegan2-faceshifter/issues/3
-   https://github.com/dayu1979/stylegan2-faceshifter/issues/1
