### ISSUE TITLE
Use latent vector

### ISSUE THREAD

**Issue by isack-ml** [woctezuma/stylegan2-projecting-images#13]
Why does latent vector editing result in a slightly different image from the original image?
![image](https://user-images.githubusercontent.com/52061393/136233911-d0e36a52-17a3-45a6-8d3d-ab519772a7a3.png)

**Comment by woctezuma** [comment]
Indeed, the model cannot replicate any photography. There are some constraints imposed on the latent vector: if you remove some of them, then the model gets better at replicating any photography, but the output is less "editable". As I mentioned in https://github.com/betterze/StyleSpace/issues/12#issuecomment-936201173, it is discussed in the paper for https://github.com/omertov/encoder4editing

That is why I would suggest to use more recent tools like `encoder4editing` to get a better trade-off.
