### ISSUE TITLE
Display the landmarks

### ISSUE THREAD

**Issue by stone100010** [woctezuma/stylegan2-projecting-images#3]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-30-663e352af38c> in <module>()
      5                   dlib_output_faces=faces,
      6                   face_no=face_no,
----> 7                   fig_size=fig_size)

<ipython-input-29-6582491cd6f9> in display_landmarks(image_name, dlib_output_faces, face_no, fig_size)
     31     face_parts = current_face.parts()
     32 
---> 33     preds = np.array([
     34                       [v.x, v.y]
     35                       for v in face_parts

NameError: name 'np' is not defined

**Comment by woctezuma** [comment]
Thanks. It looks like I forgot to:

```python
import numpy as np
```
