### ISSUE TITLE
--num-steps value

### ISSUE THREAD

**Issue by stone100010** [woctezuma/stylegan2-projecting-images#5]
python project_images.py datasets/aligned_images/ results/generated_images_tiled_10000steps/ --video True --video-mode 2

I want to get night pictures's ".npy"

Can you tell me your value of "--num-steps"?

**Comment by woctezuma** [comment]
I have not tried to modify this setting, so I use [the default value (`1000`)](https://github.com/woctezuma/stylegan2/blob/99b855b5e2e9c58eb1bcf8d0383e08001610facd/project_images.py#L86):

```python
    parser.add_argument('--num-steps', type=int, default=1000, help='Number of optimization steps')
```

By the way, if you **only** want the `.npy`, you don't need video flags (`--video True --video-mode 2`), as it slows down the process.
