### ISSUE TITLE
Stylegan2-ada 

### ISSUE THREAD

**Issue by johndpope** [woctezuma/stylegan2-projecting-images#9]
Was any efforts made to upgrade to stylegan2-ada?

**Comment by woctezuma** [comment]
No, not as far as I am concerned.

StyleGAN2-ADA introduces an adaptive strategy for non-leaky augmentation during training with limited data. It does not innovate on the projection process.

Moreover, there are different configs, so I would leave it to the user to adapt the [StyleGAN2-ADA projection code](https://github.com/NVlabs/stylegan2-ada#projecting-images-to-latent-space) for their own config. It is not a big issue. In my case, it only required removing an AssertionError as mentioned in https://github.com/NVlabs/stylegan2-ada/pull/26

**Comment by woctezuma** [comment]
Okay, one thing that the ADA repository makes easier for the user is that it saves the latent vector to `out/dlatents.npz`.

As for the `W+` projection, it was implemented in https://github.com/pbaylies/stylegan2-ada with this commit https://github.com/pbaylies/stylegan2-ada/commit/5ed61894f535d1bee332b097268f08ebfc7da926#diff-76ff8c644e89292874e4cfdf91500e696f51aa28e2912b5f6b41f92955384d1c
